//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Outsourcing_System.WorkMeterDbSyncService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncronizeDbSoap", Namespace="http://tempuri.org/")]
    public partial class SyncronizeDb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertRecordsInWorkMeterDbOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SyncronizeDb() {
            this.Url = "http://localhost:41650/SyncronizeDb.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertRecordsInWorkMeterDbCompletedEventHandler InsertRecordsInWorkMeterDbCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertRecordsInWorkMeterDb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertRecordsInWorkMeterDb(WorkMeterEntities[] cloudWmRows) {
            object[] results = this.Invoke("InsertRecordsInWorkMeterDb", new object[] {
                        cloudWmRows});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRecordsInWorkMeterDbAsync(WorkMeterEntities[] cloudWmRows) {
            this.InsertRecordsInWorkMeterDbAsync(cloudWmRows, null);
        }
        
        /// <remarks/>
        public void InsertRecordsInWorkMeterDbAsync(WorkMeterEntities[] cloudWmRows, object userState) {
            if ((this.InsertRecordsInWorkMeterDbOperationCompleted == null)) {
                this.InsertRecordsInWorkMeterDbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRecordsInWorkMeterDbOperationCompleted);
            }
            this.InvokeAsync("InsertRecordsInWorkMeterDb", new object[] {
                        cloudWmRows}, this.InsertRecordsInWorkMeterDbOperationCompleted, userState);
        }
        
        private void OnInsertRecordsInWorkMeterDbOperationCompleted(object arg) {
            if ((this.InsertRecordsInWorkMeterDbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRecordsInWorkMeterDbCompleted(this, new InsertRecordsInWorkMeterDbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkMeterEntities {
        
        private string fullNameField;
        
        private string emailField;
        
        private string userIdField;
        
        private string taskCreationDateField;
        
        private string catIdField;
        
        private string bookIdField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private string calculatedTimeField;
        
        private string commentsField;
        
        private string current_StatusField;
        
        private string targetField;
        
        private string achivedField;
        
        private string complexityField;
        
        private string end_DateField;
        
        private string expected_PagesField;
        
        private string expected_HoursField;
        
        private string resultField;
        
        private string productivity_HoursField;
        
        private string tool_UsedField;
        
        private DateWiseInfo[] dailyTimeSpentField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string TaskCreationDate {
            get {
                return this.taskCreationDateField;
            }
            set {
                this.taskCreationDateField = value;
            }
        }
        
        /// <remarks/>
        public string CatId {
            get {
                return this.catIdField;
            }
            set {
                this.catIdField = value;
            }
        }
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CalculatedTime {
            get {
                return this.calculatedTimeField;
            }
            set {
                this.calculatedTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string Current_Status {
            get {
                return this.current_StatusField;
            }
            set {
                this.current_StatusField = value;
            }
        }
        
        /// <remarks/>
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        public string Achived {
            get {
                return this.achivedField;
            }
            set {
                this.achivedField = value;
            }
        }
        
        /// <remarks/>
        public string Complexity {
            get {
                return this.complexityField;
            }
            set {
                this.complexityField = value;
            }
        }
        
        /// <remarks/>
        public string End_Date {
            get {
                return this.end_DateField;
            }
            set {
                this.end_DateField = value;
            }
        }
        
        /// <remarks/>
        public string Expected_Pages {
            get {
                return this.expected_PagesField;
            }
            set {
                this.expected_PagesField = value;
            }
        }
        
        /// <remarks/>
        public string Expected_Hours {
            get {
                return this.expected_HoursField;
            }
            set {
                this.expected_HoursField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Productivity_Hours {
            get {
                return this.productivity_HoursField;
            }
            set {
                this.productivity_HoursField = value;
            }
        }
        
        /// <remarks/>
        public string Tool_Used {
            get {
                return this.tool_UsedField;
            }
            set {
                this.tool_UsedField = value;
            }
        }
        
        /// <remarks/>
        public DateWiseInfo[] DailyTimeSpent {
            get {
                return this.dailyTimeSpentField;
            }
            set {
                this.dailyTimeSpentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateWiseInfo {
        
        private string fullNameField;
        
        private string emailField;
        
        private string bookIdField;
        
        private string timeSpentField;
        
        private string taskDateField;
        
        private string categoryIdField;
        
        private string timeRequiredField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string BookId {
            get {
                return this.bookIdField;
            }
            set {
                this.bookIdField = value;
            }
        }
        
        /// <remarks/>
        public string TimeSpent {
            get {
                return this.timeSpentField;
            }
            set {
                this.timeSpentField = value;
            }
        }
        
        /// <remarks/>
        public string TaskDate {
            get {
                return this.taskDateField;
            }
            set {
                this.taskDateField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string TimeRequired {
            get {
                return this.timeRequiredField;
            }
            set {
                this.timeRequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InsertRecordsInWorkMeterDbCompletedEventHandler(object sender, InsertRecordsInWorkMeterDbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRecordsInWorkMeterDbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRecordsInWorkMeterDbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591